Repository data301-2020-winter2/course-project-group_1039, pull requests merged in 2021-03, with the labels that each got.

#28 edit citation and format
  README.md
Labels: documentation

#27 Edit script for init data processing
  analysis/Jamie/milestones2.ipynb
  analysis/scripts/project_functions.py
Labels: enhancement, help wanted

#31 help fix last graph on region analysis
  analysis/Rita/Milestonr2_EDA.ipynb
Labels: bug

#32 Milestone2 jamie
  analysis/Jamie/milestones2.ipynb
  analysis/Jamie/milestones2_EDA.ipynb
Labels: bug, enhancement

#33 remove horizontal line and misplaced symlinks
  README.md
  Rita
Labels: bug, documentation

#35 Milestone2 jamie
  analysis/Jamie/milestones2_EDA.ipynb
Labels: Task, enhancement

#36 Rita EDA done
  analysis/Jamie/milestones2_EDA.ipynb
  analysis/Leo/markdownPractise.ipynb
  analysis/Rita/Milestonr2_EDA.ipynb
Labels: Task, enhancement

#37 format plot design
  analysis/Jamie/milestones2_EDA.ipynb
  analysis/Rita/Milestonr2_EDA.ipynb
Labels: enhancement

#40 create group analysis file, combine states analysis
  analysis/Group Analysis.ipynb
  analysis/Jamie/milestones2_EDA.ipynb
  analysis/Leo/milestone1.ipynb
  analysis/Rita/Milestonr2_EDA.ipynb
  analysis/Untitled.ipynb
Labels: documentation

#41 Milestone2 jamie
  analysis/Group Analysis.ipynb
  analysis/Jamie/milestones2_EDA.ipynb
  analysis/Rita/Milestonr2_EDA.ipynb
  analysis/Untitled.ipynb
  analysis/submitted/analysis.ipynb
  analysis/submitted/scripts
Labels: Task, enhancement

#43 Collective analysis
  analysis/submitted/analysis.ipynb
Labels: bug, enhancement

#46 Group analysis done
  analysis/Rita/Milestonr2_EDA.ipynb
  analysis/submitted/analysis.ipynb
Labels: enhancement
